export * from './actionAttributePermissionsResource.service';
import { ActionAttributePermissionsResourceService } from './actionAttributePermissionsResource.service';
export * from './actionManageRelationshipsResource.service';
import { ActionManageRelationshipsResourceService } from './actionManageRelationshipsResource.service';
export * from './entityDeleteByIdResource.service';
import { EntityDeleteByIdResourceService } from './entityDeleteByIdResource.service';
export * from './entityGetByIdResource.service';
import { EntityGetByIdResourceService } from './entityGetByIdResource.service';
export * from './pageExtendedEventResource.service';
import { PageExtendedEventResourceService } from './pageExtendedEventResource.service';
export * from './pageExtendedProjectResource.service';
import { PageExtendedProjectResourceService } from './pageExtendedProjectResource.service';
export * from './pageListAccountsResource.service';
import { PageListAccountsResourceService } from './pageListAccountsResource.service';
export * from './pageListEventsResource.service';
import { PageListEventsResourceService } from './pageListEventsResource.service';
export * from './pageListPermissionsResource.service';
import { PageListPermissionsResourceService } from './pageListPermissionsResource.service';
export * from './pageListProjectsResource.service';
import { PageListProjectsResourceService } from './pageListProjectsResource.service';
export * from './pageListTagsResource.service';
import { PageListTagsResourceService } from './pageListTagsResource.service';
export * from './pageLoginResource.service';
import { PageLoginResourceService } from './pageLoginResource.service';
export * from './pageUpsertAccountResource.service';
import { PageUpsertAccountResourceService } from './pageUpsertAccountResource.service';
export * from './pageUpsertEventResource.service';
import { PageUpsertEventResourceService } from './pageUpsertEventResource.service';
export * from './pageUpsertProjectResource.service';
import { PageUpsertProjectResourceService } from './pageUpsertProjectResource.service';
export * from './pageUpsertTagResource.service';
import { PageUpsertTagResourceService } from './pageUpsertTagResource.service';
export * from './pageUpsertTenantResource.service';
import { PageUpsertTenantResourceService } from './pageUpsertTenantResource.service';
export const APIS = [ActionAttributePermissionsResourceService, ActionManageRelationshipsResourceService, EntityDeleteByIdResourceService, EntityGetByIdResourceService, PageExtendedEventResourceService, PageExtendedProjectResourceService, PageListAccountsResourceService, PageListEventsResourceService, PageListPermissionsResourceService, PageListProjectsResourceService, PageListTagsResourceService, PageLoginResourceService, PageUpsertAccountResourceService, PageUpsertEventResourceService, PageUpsertProjectResourceService, PageUpsertTagResourceService, PageUpsertTenantResourceService];
