export * from './pageCreateEventoResource.service';
import { PageCreateEventoResourceService } from './pageCreateEventoResource.service';
export * from './pageCreateProjetoResource.service';
import { PageCreateProjetoResourceService } from './pageCreateProjetoResource.service';
export * from './pageCreateTenantResource.service';
import { PageCreateTenantResourceService } from './pageCreateTenantResource.service';
export * from './pageCreateUsuarioResource.service';
import { PageCreateUsuarioResourceService } from './pageCreateUsuarioResource.service';
export * from './pageListarEventosResource.service';
import { PageListarEventosResourceService } from './pageListarEventosResource.service';
export * from './pageListarProjetosOfEventoResource.service';
import { PageListarProjetosOfEventoResourceService } from './pageListarProjetosOfEventoResource.service';
export * from './pageListarProjetosResource.service';
import { PageListarProjetosResourceService } from './pageListarProjetosResource.service';
export * from './pageListarUsuariosResource.service';
import { PageListarUsuariosResourceService } from './pageListarUsuariosResource.service';
export * from './pageLoginResource.service';
import { PageLoginResourceService } from './pageLoginResource.service';
export const APIS = [PageCreateEventoResourceService, PageCreateProjetoResourceService, PageCreateTenantResourceService, PageCreateUsuarioResourceService, PageListarEventosResourceService, PageListarProjetosOfEventoResourceService, PageListarProjetosResourceService, PageListarUsuariosResourceService, PageLoginResourceService];
