export * from './pageAtribuirPermissoesResource.service';
import { PageAtribuirPermissoesResourceService } from './pageAtribuirPermissoesResource.service';
export * from './pageCreateEventoResource.service';
import { PageCreateEventoResourceService } from './pageCreateEventoResource.service';
export * from './pageCreateProjetoResource.service';
import { PageCreateProjetoResourceService } from './pageCreateProjetoResource.service';
export * from './pageCreateTenantResource.service';
import { PageCreateTenantResourceService } from './pageCreateTenantResource.service';
export * from './pageCreateUsuarioResource.service';
import { PageCreateUsuarioResourceService } from './pageCreateUsuarioResource.service';
export * from './pageDetalhesEventoResource.service';
import { PageDetalhesEventoResourceService } from './pageDetalhesEventoResource.service';
export * from './pageListarEventosResource.service';
import { PageListarEventosResourceService } from './pageListarEventosResource.service';
export * from './pageListarProjetosResource.service';
import { PageListarProjetosResourceService } from './pageListarProjetosResource.service';
export * from './pageListarTagsResource.service';
import { PageListarTagsResourceService } from './pageListarTagsResource.service';
export * from './pageListarUsuariosResource.service';
import { PageListarUsuariosResourceService } from './pageListarUsuariosResource.service';
export * from './pageLoginResource.service';
import { PageLoginResourceService } from './pageLoginResource.service';
export * from './pageRegistrarProjetoEmEventoResource.service';
import { PageRegistrarProjetoEmEventoResourceService } from './pageRegistrarProjetoEmEventoResource.service';
export const APIS = [PageAtribuirPermissoesResourceService, PageCreateEventoResourceService, PageCreateProjetoResourceService, PageCreateTenantResourceService, PageCreateUsuarioResourceService, PageDetalhesEventoResourceService, PageListarEventosResourceService, PageListarProjetosResourceService, PageListarTagsResourceService, PageListarUsuariosResourceService, PageLoginResourceService, PageRegistrarProjetoEmEventoResourceService];
