/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TagDto } from './tagDto';


export interface AccountDto { 
    id: number;
    idTenant: number;
    login: string;
    email?: string;
    firstName: string;
    lastName: string;
    tags: Array<TagDto>;
}

