/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AttributePermissionsDto { 
    idTenant: number;
    idAccounts: Array<number>;
    idPermissions: Array<number>;
}

