/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TagDto } from './tagDto';
import { AccountDto } from './accountDto';


export interface EventDto { 
    id: number;
    idTenant: number;
    title: string;
    description: string;
    owner: AccountDto;
    tags: Array<TagDto>;
}

