/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ListarEventosDto { 
    id: number;
    title: string;
    description: string;
    createdByIdAccount: number;
    createdByNameAccount: string;
    bannerUrl?: string;
    userIsMember: boolean;
}

