/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginInformationResponseDto { 
    idAccount: number;
    idTenant: number;
    idPerson?: number;
    login: string;
    tenantTitle: string;
    firstName?: string;
    lastName?: string;
}

