/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TenantDto } from './tenantDto';
import { EventDto } from './eventDto';
import { TagDto } from './tagDto';


export interface ProjectDto { 
    id: number;
    idTenant: number;
    title: string;
    description: string;
    tenant: TenantDto;
    tags: Array<TagDto>;
    events: Array<EventDto>;
}

