/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterViewDto { 
    idTenant: number;
    idAccount: number;
    idRef: number;
    entityRef: RegisterViewDto.EntityRefEnum;
}
export namespace RegisterViewDto {
    export type EntityRefEnum = 'EVENT' | 'PROJECT' | 'TAG';
    export const EntityRefEnum = {
        Event: 'EVENT' as EntityRefEnum,
        Project: 'PROJECT' as EntityRefEnum,
        Tag: 'TAG' as EntityRefEnum
    };
}


