/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpsertAccountDto { 
    idTenant: number;
    email: string;
    login: string;
    password: string;
    firstName: string;
    lastName: string;
    tags: Array<number>;
}

