/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpsertEventDto { 
    idAccount: number;
    idTenant: number;
    title: string;
    description: string;
    bannerUrl?: string;
    tags: Array<number>;
}

