/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpsertTagDto { 
    idTenant: number;
    title: string;
    forProjects: boolean;
    forEvents: boolean;
    forAccounts: boolean;
}

