/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateProjetoDto { 
    idTenant: number;
    title: string;
    description: string;
    eventosSelecionados: Array<number>;
}

