spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_dev
    username: evoge_user
    password: evoge_pass
    name: test_dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
