spring:
  application:
    name: synergia
  config:
    import:
      - "classpath:application-server.yaml"
      - "classpath:application-springdoc.yaml"
#      - "classpath:application-datasource.yaml"
      - "classpath:application-datasource-windows.yaml"