spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/synergia_dev
    username: raindrop
    password: Admin
    name: synergia_dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
