spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/repo_test
    username: evoge_user
    password: evoge_pass
    name: repo_test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
